apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/fixgramwork/swelling-fastapi-server
    newName: swelling-fastapi-server
    newTag: local
